/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Hamburger: typeof import('./src/components/Hamburger/Hamburger.vue')['default']
    Navbar: typeof import('./src/layout/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/layout/components/SideBar/SideBar.vue')['default']
    SideBarItem: typeof import('./src/layout/components/SideBar/SideBarItem.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
  }
}
