/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/layout/components/AppMain.vue')['default']
    Avatar: typeof import('./src/components/Avatar/Avatar.vue')['default']
    Breadcrumb: typeof import('./src/layout/components/Breadcrumb/Breadcrumb.vue')['default']
    copy: typeof import('./src/components/Setting/Setting copy.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Hamburger: typeof import('./src/components/Hamburger/Hamburger.vue')['default']
    Navbar: typeof import('./src/layout/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./src/components/Screenfull/Screenfull.vue')['default']
    Setting: typeof import('./src/components/Setting/Setting.vue')['default']
    SettingDetail: typeof import('./src/components/Setting/SettingDetail.vue')['default']
    SideBar: typeof import('./src/layout/components/SideBar/SideBar.vue')['default']
    SideBarItem: typeof import('./src/layout/components/SideBar/SideBarItem.vue')['default']
    SideBarItemLink: typeof import('./src/layout/components/SideBar/SideBarItemLink.vue')['default']
    SideLogo: typeof import('./src/layout/components/SideBar/SideLogo.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect/SizeSelect.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    TagsView: typeof import('./src/layout/components/TagsView/TagsView.vue')['default']
  }
}
